DV_prevention/DV_prevention/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('user_auth.urls', 'user_auth'), namespace='user_auth')),
    path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include(('user_requests.urls', 'user_requests'), namespace='user_requests')),
    path('complaints/', include(('complaints.urls', 'complaints'), namespace='complaints')),
]

DV_prevention/accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'accounts'

urlpatterns = [
	path('profile/<str:profile_slug>/', views.profileView, name = 'profile-view'),
	path('profile-file-drop/', views.profile_drop_zone_file, name = 'profile-file-drop-zone-view'),
	path('profile-file-drop/upload/', views.profile_file_upload_view, name = 'profile-file-drop-upload-upload-view'),
	path('edit-profile/', views.profileEdit, name = 'profile-edit'),
	path('profile-rate/<str:profile_slug>/', views.profileRate, name='profile-rate'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,
	document_root = settings.MEDIA_ROOT)

DV_prevention/user_auth/urls.py
from django.urls import path, include
from . import views
from complaints.views import exploreComplaints
app_name = 'user-auth'

urlpatterns = [
	path('', exploreComplaints),
	path('register/', views.registerPage, name='register'),
	path('login/', views.loginPage, name='login'),
	path('logout/', views.logoutUser, name='logout'),
]

DV_prevention/user_auth/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from accounts.models import User
from django import forms

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2', 'user_role']

DV_prevention/user_auth/views.py
from .decorators import auth_or_not
from .forms import CreateUserForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.shortcuts import render, redirect, HttpResponse
from django.urls import reverse
from accounts.models import User
from user_requests.models import Contact_Request, Complaint_Request
from django.views.decorators.csrf import csrf_protect
# Create your views here.

def nullDetails(request):
	if(request.user.user_phone is None or request.user.user_phone == "None"):
		return True
	if(request.user.user_place is None or request.user.user_place == "None"):
		return True
	if(request.user.user_description is None or request.user.user_description == "None"):
		return True

@csrf_protect
@auth_or_not(0)
def registerPage(request):
	form = CreateUserForm()
	if request.method == 'POST':
		form = CreateUserForm(request.POST)
		if form.is_valid():
			form.save()
			user_name = form.cleaned_data.get('username')

			messages.success(request, 'Account was created for ' + user_name)

			return redirect('user_auth:login')
	context = {'form':form}
	return render(request, 'user_auth/register.html', context)

@csrf_protect
@auth_or_not(0)
def loginPage(request):
	if request.method == "POST":
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(username=username, password=password)
		if user is not None:
			login(request, user)
			if nullDetails(request):
				return redirect('accounts:profile-edit')
			return redirect('complaints:explore-complaints')
		else:
			messages.info(request, 'Incorrect Username and Password combination')
	return render(request, 'user_auth/login.html')

@auth_or_not(1)
def logoutUser(request):
	logout(request)
	return redirect('user_auth:login')

DV_prevention/user_auth/templates/user_auth/login.html
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Courgette|Lobster">

<style>
  .gradient-custom-2 {
    background-color: #AC3B61;
    color: #EDC7B7;
  }

    @media (min-width: 768px) {
        .gradient-form {
        height: 100vh !important;
        }
    }
    @media (min-width: 769px) {
        .gradient-custom-2 {
        border-top-right-radius: .3rem;
        border-bottom-right-radius: .3rem;
        }
    }
    #messages{
        background-color: #AC3B61;
        color: #EDC7B7;
        padding: 10px;
        margin-top: 10px;
    }
</style>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Aguafina+Script|Dancing+Script|Kaushan+Script|Open+Sans|Petit+Formal+Script|Pinyon+Script|Roboto|Rouge+Script" rel="stylesheet">

<section class="h-100 gradient-form" style="background-color: #EEE2DC;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-xl-10">
          <div class="card rounded-3 text-black">
            <div class="row g-0">
              <div class="col-lg-6" style="background-color: #EDC7B7;">
                <div class="card-body p-md-5 mx-md-4">
                  <!-- <div class="text-center">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/lotus.webp"
                      style="width: 185px;" alt="logo">
                    <h4 class="mt-1 mb-5 pb-1">We are The Lotus Team</h4>
                  </div> -->
                  <form method="POST" action="">
                    {% csrf_token %}
                    <p style="text-align: center; color: #AC3B61; font-family: Courgette;">Please login to your account</p>
  
                    <div class="form-outline mb-4">
                        <input type="text"  id="form2Example11" name="username" placeholder="Username..." class="form-control">
                        <label class="form-label" for="form2Example11" style="color: #AC3B61;">Username</label>
                    </div>
  
                    <div class="form-outline mb-4">
                        <input type="password" id="form2Example22"  name="password" placeholder="Password..." class="form-control" />
                        <label class="form-label" for="form2Example22" style="color: #AC3B61;">Password</label>
                    </div>

                    {% for message in messages %}
                    <p id="messages">{{message}}</p>
                    {% endfor %}
  
                    <div class="text-center pt-1 mb-5 pb-1">
                        <div class="pt-1 mb-4">
                            <input class="btn btn-lg btn-block gradient-custom-2" style="font-family: Courgette;" 
                            type="submit" value="Login">
                        </div>
                    </div>
                    
                    <div class="d-flex align-items-center justify-content-center pb-4">
                      <p class="mb-0 me-2" style="color: #AC3B61; font-family: Courgette;">Don't have an account?</p>
                      <a href="{% url 'user-auth:register' %}" class="ml-2"><button type="button" class="btn btn-outline-danger ml-3">Create new</button></a>
                    </div>
  
                  </form>
  
                </div>
              </div>
              <div class="col-lg-6 d-flex align-items-center gradient-custom-2">
                <div class="text-black px-3 py-4 p-md-5 mx-md-4">
                  <h1 class="mb-4" style="font-family: 'Lobster';">DV Prevention</h1>
                  <h5 style="font-family: 'Courgette';">An initiative to reduce Domestic Violence across India</h5>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

DV_prevention/user_auth/templates/user_auth/register.html
{% load widget_tweaks %}

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Courgette|Lobster">

<style>
    .gradient-custom-2 {
      background-color: #AC3B61;
      color: #EDC7B7;
    }

    @media (min-width: 768px) {
        .gradient-form {
        height: 100vh !important;
        }
    }
    @media (min-width: 769px) {
        .gradient-custom-2 {
        border-top-right-radius: .3rem;
        border-bottom-right-radius: .3rem;
        }
    }
    #messages{
        background-color: #AC3B61;
        color: #EDC7B7;
        padding: 10px;
        margin-top: 10px;
    }
</style>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Aguafina+Script|Dancing+Script|Kaushan+Script|Open+Sans|Petit+Formal+Script|Pinyon+Script|Roboto|Rouge+Script" rel="stylesheet">

<section class="h-100 gradient-form" style="background-color: #EEE2DC;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-xl-10">
          <div class="card rounded-3 text-black">
            <div class="row g-0">
              <div class="col-lg-6" style="background-color: #EDC7B7;">
                <div class="card-body p-md-5 mx-md-4">
                  <!-- <div class="text-center">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/lotus.webp"
                      style="width: 185px;" alt="logo">
                    <h4 class="mt-1 mb-5 pb-1">We are The Lotus Team</h4>
                  </div> -->
                  <form method="POST" action="">
                    {% csrf_token %}
                    <p style="text-align: center; color: #AC3B61; font-family: Courgette;">Register Now</p>
  
                    <div class="form-outline mb-4">
                        {% render_field form.username id="form2Example11" name="username" type="text" placeholder="Username..." class="form-control" %}
                    </div>

                    <div class="form-outline mb-4">
                        {% render_field form.email id="form2Example11" name="email" type="email" placeholder="Email..." class="form-control" %}
                    </div>
  
                    <div class="form-outline mb-4">
                        {% render_field form.password1 id="form2Example11" name="password1" type="password" placeholder="Enter your password..." class="form-control" %}
                    </div>

                    <div class="form-outline mb-4">
                        {% render_field form.password2 id="form2Example11" name="password2" type="password" placeholder="Enter your password again..." class="form-control" %}
                    </div>

                    <div class="form-outline mb-4">
                        {% render_field form.user_role id="form2Example11" name="user_role" type="text" class="form-control" %}
                    </div>

                    {{form.errors}}

                    <div class="text-center pt-1 mb-5 pb-1">
                        <div class="pt-1 mb-4">
                            <input class="btn btn-lg btn-block gradient-custom-2"  style="font-family: Courgette;" 
                            type="submit" value="Register">
                        </div>
                    </div>
  
                    <div class="d-flex align-items-center justify-content-center pb-4">
                      <p class="mb-0 me-2" style="color: #AC3B61; font-family: 'Courgette'">Already have an account?</p>
                      <a href="{% url 'user-auth:login' %}" class="ml-2"><button type="button" class="btn btn-outline-danger ml-3">Login</button></a>
                    </div>
  
                  </form>
  
                </div>
              </div>
              <div class="col-lg-6 d-flex align-items-center gradient-custom-2">
                <div class="text-black px-3 py-4 p-md-5 mx-md-4">
                  <h1 class="mb-4" style="font-family: 'Lobster';">DV Prevention</h1>
                  <h5 style="font-family: 'Courgette';">An initiative to reduce Domestic Violence across India</h5>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>