DV_prevention/DV_prevention/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('user_auth.urls', 'user_auth'), namespace='user_auth')),
    path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include(('user_requests.urls', 'user_requests'), namespace='user_requests')),
    path('complaints/', include(('complaints.urls', 'complaints'), namespace='complaints')),
]

DV_prevention/accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'accounts'

urlpatterns = [
	path('profile/<str:profile_slug>/', views.profileView, name = 'profile-view'),
	path('profile-file-drop/', views.profile_drop_zone_file, name = 'profile-file-drop-zone-view'),
	path('profile-file-drop/upload/', views.profile_file_upload_view, name = 'profile-file-drop-upload-upload-view'),
	path('edit-profile/', views.profileEdit, name = 'profile-edit'),
	path('profile-rate/<str:profile_slug>/', views.profileRate, name='profile-rate'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,
	document_root = settings.MEDIA_ROOT)

DV_prevention/complaints/urls.py
from django.urls import path
from . import views
app_name = 'complaints'

urlpatterns = [
	path('', views.exploreComplaints, name='explore-complaints'),
	path('tag/#<str:complaint_tag>/', views.exploreComplaintsByTag, name='explore-complaints-by-tag'),
	path('request-history/', views.requestHistory, name = 'request-history'),
	path('find-nearest-helpers/', views.findNearestActivist, name='complaint-request-nearest-activist'),
	path('complaint-file-drop/', views.complaint_drop_zone_file, name = 'complaint-file-drop-zone-view'),
	path('complaint-file-drop/upload/', views.complaint_file_upload_view, name = 'complaint-file-drop-upload-upload-view'),
	path('investigate/<str:complaint_id>/', views.investigateComplaint, name='investigate-complaint'),
	path('mark-as-done/<str:complaint_id>/', views.markComplaintAsDone, name='mark-as-done'),
	path('create-complaint/', views.createComplaint, name='create-complaint'),
	path('delete_complaint/<str:complaint_id>/', views.deleteComplaint, name='delete-complaint'),
	path('<str:complaint_id>/', views.showComplaintDetail, name='show-complaint-detail'),
	path('<str:complaint_id>/<str:message_type>/', views.addMessage, name='update-complaint'),
	path('<str:complaint_id>/vote_change/upvote/', views.complaintUpvote, name='upvote-complaint'),
	path('<str:complaint_id>/vote_change/downvote/', views.complaintDownvote, name='downvote-complaint'),
	path('<str:complaint_id>/<str:message_type>/', views.addMessage, name='update-complaint'),
]

DV_prevention/user_auth/urls.py
from django.urls import path, include
from . import views
from complaints.views import exploreComplaints
app_name = 'user-auth'

urlpatterns = [
	path('', exploreComplaints),
	path('register/', views.registerPage, name='register'),
	path('login/', views.loginPage, name='login'),
	path('logout/', views.logoutUser, name='logout'),
]

DV_prevention/user_requests/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'user_requests'

urlpatterns = [
	path('verify-user/<str:profile_id>/', views.verifyUser,name = 'verify-user'),
	path('report-user/<str:profile_id>/', views.reportUser,name = 'report-user'),
	path('request-contact-info/<str:profile_id>/', views.requestContactInfo,name = 'request-contact-info'),
	path('show-contact-requests/', views.showContactRequests, name = 'show-contact-requests'),
	path('show-complaint-requests/', views.showComplaintRequests, name = 'show-complaint-requests'),
	path('contact-request-action/<str:request_id>/<int:action>/', views.requestContactInfoAction, name = 'request-contact-info-action'),
	path('complaint-request-action/<str:profile_id>/', views.requestComplaintAction, name = 'request-complaint-action'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,
	document_root = settings.MEDIA_ROOT)

DV_prevention/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.template.defaultfilters import slugify
# Create your models here.

class User(AbstractUser):
	role_choices = (
		('Normal user/Victim', 'Normal user/Victim'), 
		('NGO/Activist/Mod', 'NGO/Activist/Mod'),
	)
	user_phone = 				models.CharField(max_length = 200, unique = True, null = True, blank = True)
	user_other =  				models.TextField(null = True, blank = True)
	user_profile_image =  		models.ImageField(null = True, upload_to = 'profiles', default = 'profiles/default-image.jpg')
	user_role = 				models.CharField(max_length = 50, null = True, choices = role_choices)
	user_complaints_solved = 	models.PositiveIntegerField(default = 0)
	user_description = 			models.TextField(null = True, blank = True)
	user_place = 				models.CharField(max_length = 1000, null = True, blank = True)
	user_place_geocode = 		models.JSONField(null = True, blank = True)
	user_notifications = 		models.PositiveIntegerField(default = 0)
	slug = 						models.SlugField(unique=True, max_length=100, default='some string')

	def __str__(self):
		return str(self.username)

	def save(self, *args, **kwargs):
		self.slug = slugify(self.username)
		super(User, self).save(*args, **kwargs)

class User_Document(models.Model):
	user_name = 			models.ForeignKey(User, null = True, on_delete = models.CASCADE, related_name = 'user_documents')
	user_file = 			models.ImageField(null = True, upload_to = 'identity')
	
	def __str__(self):
		return str(self.user_file)

class Rating(models.Model):
	rating_from = 			models.ForeignKey(User, null = True, on_delete = models.CASCADE, related_name='rating_from')
	rating_to = 			models.ForeignKey(User, null = True, on_delete = models.CASCADE, related_name='rating_to')
	rating_score = 			models.FloatField(default = 0.0)

	def __str__(self):
		return str(self.rating_from) + " to " + str(self.rating_to)

DV_prevention/accounts/forms.py
from django import forms
from .models import User, User_Document
import json

class User_Documents_Form(forms.ModelForm):
	class Meta:
		model = User_Document
		fields = ['user_file']

class UpdateUserForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['username', 'user_phone', 'user_other', 'email', 'user_description', 'user_profile_image', 'user_place', 'user_place_geocode']
	
	def save(self, commit=True):
		user = super(UpdateUserForm, self).save(commit = False)
		user.email = self.cleaned_data['email']
		user.user_phone = self.cleaned_data['user_phone']
		user.user_description = self.cleaned_data['user_description']
		if(self.cleaned_data['user_profile_image'] is not None):
			user.user_profile_image = self.cleaned_data['user_profile_image']
		if user.user_place_geocode is not None:
			user.user_place = user.user_place_geocode['place_name']
		user.user_other = self.cleaned_data['user_other']
		# user.user_profile_image = self.cleaned_data['user_profile_image']
		if commit:
			return user.save()
		else:
			return user

"""
def clean_email(self):
	user_description = self.cleaned_data.get('email')
	user_profile_image = self.cleaned_data.get('email')

	if email and User.objects.filter(email=email).exclude(username=username).count():
		raise forms.ValidationError('This email address is already in use. Please supply a different email address.')
	return email
"""

DV_prevention/accounts/views.py
from .forms import UpdateUserForm
from .models import *
from django.shortcuts import render, reverse, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.views.generic import TemplateView
from user_auth.decorators import auth_or_not
from user_requests.models import *

# Create your views here.

@login_required(login_url='user_auth:login')
@auth_or_not(1)
def profileView(request, profile_slug):
	"""
	View the profile
	"""
	profile = User.objects.get(slug = profile_slug)
	verifications_count = Verification.objects.filter(verified_user = profile).count()
	report_count = Report.objects.filter(reported_user = profile).count()
	user_documents = User_Document.objects.filter(user_name = profile)
	contact_permitted_instances = Contact_Permission.objects.filter(permitted_user = request.user)

	complaint_request_sent = False
	if(Complaint.objects.filter(complaint_filer = request.user).exists()):
		complaint = Complaint.objects.get(complaint_filer = request.user)
		complaint_request_sent = Complaint_Request.objects.filter(requested_by = request.user, requested_user = profile, 
		requested_complaint = complaint).exists()
	
	contact_request_sent = Contact_Request.objects.filter(requested_by = request.user, requested_user = profile).exists()

	total_profile_ratings = Rating.objects.filter(rating_to = profile).count()
	total_profile_score = 0
	for i in Rating.objects.filter(rating_to = profile):
		total_profile_score += i.rating_score

	total_profile_score /= max(total_profile_ratings, 1)
	total_profile_score = round(total_profile_score, 2)
	user_current_rating = 0
	if Rating.objects.filter(rating_from = request.user, rating_to = profile).exists():
		user_current_rating = Rating.objects.get(rating_from = request.user, rating_to = profile).rating_score

	permitted_user = Contact_Permission.objects.filter(permitted_user = request.user, permitted_by = profile).exists()
	if profile.user_role == 'NGO/Activist/Mod' or profile == request.user:
		permitted_user = True
	
	contact_permitted_users = []
	for i in contact_permitted_instances:
		contact_permitted_users.append(i.permitted_user)

	user_complaint_availible = Complaint.objects.filter(complaint_filer = request.user).exists()
	user_in_contact = Contact_Permission.objects.filter(permitted_by = profile, permitted_user = request.user).exists()

	context = {'profile':profile, 'user_documents':user_documents, 'verifications_count':verifications_count,
	'contact_permitted_users':contact_permitted_users, 'contact_request_sent':contact_request_sent, 
	'report_count':report_count, 'permitted_user':permitted_user, 'total_profile_score':total_profile_score, 
	'user_current_rating':user_current_rating, 'user_complaint_availible':user_complaint_availible, 
	'complaint_request_sent': complaint_request_sent, 'user_in_contact': user_in_contact}
	return render(request, 'accounts/profile.html', context)

@login_required(login_url='user_auth:login')
@auth_or_not(1)
def profileEdit(request):
	"""
	Edit Profile
	"""
	form = UpdateUserForm()

	if request.method == "POST":
		form = UpdateUserForm(request.POST, request.FILES, instance=request.user)
		if form.is_valid():
			form.save()
		else:
			print(form.errors)
		return redirect('/')
	context = {'user':request.user, 'form':form}
	return render(request, 'accounts/profile_edit_form.html', context)

@login_required(login_url='user_auth:login')
@auth_or_not(1)
def profileRate(request, profile_slug):
	profile = User.objects.get(slug = profile_slug)
	if(Rating.objects.filter(rating_from = request.user, rating_to = profile).exists()):
		Rating.objects.filter(rating_from = request.user, rating_to = profile).delete()
	Rating.objects.create(rating_score = int(request.POST.get('slider-value')), rating_from = request.user, rating_to = profile)
	return redirect(reverse('accounts:profile-view', kwargs={'profile_slug':profile_slug}))

@login_required(login_url='user_auth:login')
@auth_or_not(1)
def profile_drop_zone_file(request):
	context = {}
	return render(request, 'accounts/profile_drop_zone.html', context)

@login_required(login_url='user_auth:login')
@auth_or_not(1)
def profile_file_upload_view(request):
	"""
	Upload Verification files
	"""
	if request.method == "POST":
		my_file = request.FILES.get('file')
		if(str(my_file).endswith('jpg') or str(my_file).endswith('jpeg') or str(my_file).endswith('jfif') or str(my_file).endswith('pjpeg') or str(my_file).endswith('pjp') or str(my_file).endswith('png')):
			user_document = User_Document.objects.create(user_name = request.user, user_file = my_file)
		else:
			pass
		return redirect('/')
	return JsonResponse({'post':'false'})

DV_prevention/accounts/templates/accounts/navbar.html
{% load static %}
{% load custom_tags %}

<style>
  @import url('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css');
  @import url('https://fonts.googleapis.com/css?family=Roboto');

/*----------bootstrap-navbar-css------------*/
.navbar-logo{
	padding: 15px;
	color: #EEE2DC;
}
.navbar-mainbg{
	background-color: #AC3B61;
	padding: 0px;
}
#navbarSupportedContent{
	overflow: hidden;
	position: relative;
}
#navbarSupportedContent ul{
	padding: 0px;
	margin: 0px;
}
#navbarSupportedContent ul li a i{
	margin-right: 10px;
}
#navbarSupportedContent li {
	list-style-type: none;
	float: left;
}
#navbarSupportedContent ul li a{
	color: rgba(255,255,255,0.5);
    text-decoration: none;
    font-size: 15px;
    display: block;
    padding: 20px 20px;
    transition-duration:0.6s;
	transition-timing-function: cubic-bezier(0.68, -0.55, 0.265, 1.55);
    position: relative;
}
#navbarSupportedContent>ul>li.active>a{
	color: #AC3B61;
	background-color: transparent;
	transition: all 0.7s;
}
#navbarSupportedContent a:not(:only-child):after {
	content: "\f105";
	position: absolute;
	right: 20px;
	top: 10px;
	font-size: 14px;
	font-family: "Font Awesome 5 Free";
	display: inline-block;
	padding-right: 3px;
	vertical-align: middle;
	font-weight: 900;
	transition: 0.5s;
}
#navbarSupportedContent .active>a:not(:only-child):after {
	transform: rotate(90deg);
}
.hori-selector{
	display:inline-block;
	position:absolute;
	height: 100%;
	top: 0px;
	left: 0px;
	transition-duration:0.6s;
	transition-timing-function: cubic-bezier(0.68, -0.55, 0.265, 1.55);
	background-color: #EEE2DC;
	border-top-left-radius: 15px;
	border-top-right-radius: 15px;
	margin-top: 10px;
}
.hori-selector .right,
.hori-selector .left{
	position: absolute;
	width: 25px;
	height: 25px;
	background-color: #EEE2DC;
	bottom: 10px;
}
.hori-selector .right{
	right: -25px;
}
.hori-selector .left{
	left: -25px;
}
.hori-selector .right:before,
.hori-selector .left:before{
	content: '';
    position: absolute;
    width: 50px;
    height: 50px;
    border-radius: 50%;
    background-color: #AC3B61;
}
.hori-selector .right:before{
	bottom: 0;
    right: -25px;
}
.hori-selector .left:before{
	bottom: 0;
    left: -25px;
}


@media(min-width: 992px){
	.navbar-expand-custom {
	    -ms-flex-flow: row nowrap;
	    flex-flow: row nowrap;
	    -ms-flex-pack: start;
	    justify-content: flex-start;
	}
	.navbar-expand-custom .navbar-nav {
	    -ms-flex-direction: row;
	    flex-direction: row;
	}
	.navbar-expand-custom .navbar-toggler {
	    display: none;
	}
	.navbar-expand-custom .navbar-collapse {
	    display: -ms-flexbox!important;
	    display: flex!important;
	    -ms-flex-preferred-size: auto;
	    flex-basis: auto;
	}
}


@media (max-width: 991px){
	#navbarSupportedContent ul li a{
		padding: 12px 30px;
	}
	.hori-selector{
		margin-top: 0px;
		margin-left: 10px;
		border-radius: 0;
		border-top-left-radius: 25px;
		border-bottom-left-radius: 25px;
	}
	.hori-selector .left,
	.hori-selector .right{
		right: 10px;
	}
	.hori-selector .left{
		top: -25px;
		left: auto;
	}
	.hori-selector .right{
		bottom: -25px;
	}
	.hori-selector .left:before{
		left: -25px;
		top: -25px;
	}
	.hori-selector .right:before{
		bottom: -25px;
		left: -25px;
	}
	.navbar-mainbg{
		background-color: #AC3B61;
		padding: 0px;
	}
}

@keyframes blinking_notification_animation {
	0% {
		opacity: 0;
	}

	50% {
		opacity: 0.7;
	}

	100% {
		opacity: 0;
	}
}

a, a:hover, a:visited, a:active {
  color: inherit;
  text-decoration: none;
 }

.notification-badge-animation {
	animation: blinking_notification_animation 1.5s linear infinite;
	border-radius: 50%;
	color: #AC3B61;
	/* width: 15px;
	height: 15px;
	padding: 10px; */
	background: #EEE2DC;
	
}

</style>
<nav class="navbar navbar-expand-custom navbar-mainbg">
	<button class="navbar-toggler" type="button" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<i class="fas fa-bars text-white"></i>
	</button>
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<li class="nav-item ml-4" style="background-color: #EEE2DC; color: #AC3B61">
			<a class="nav-link" href="{% url 'user_auth:logout' %}"><i class="fa fa-solid fa-right-from-bracket"></i>Logout</a>
		</li>
		<ul class="navbar-nav ml-auto" id="navbar-menu">
			<div class="hori-selector">
				<div class="left"></div>
				<div class="right"></div>
			</div>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'complaints:explore-complaints' %}"><i class="fas fa-tachometer-alt"></i>Explore</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'complaints:request-history' %}"><i class="fa fa-solid fa-list"></i>Request History</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'complaints:create-complaint' %}"><i class="far fa-clone"></i>Create Complaint</a>
			</li>
			<li class="nav-item">
				{% if request.user.user_role == 'Normal user/Victim' %}
					<a class="nav-link" href="{% url 'user_requests:show-contact-requests' %}">
						<i class="fa fa-solid fa-newspaper"></i>
						Contact Requests
						
						{% if request.user.is_authenticated %}
						{% if not request.user.user_notifications %}
						<span class="badge" id="notification-badge">
							0
						</span>
						{% else %}
						<span class="badge notification-badge-animation" id="notification-badge">
							{{request.user.user_notifications}}
						</span>
						{% endif %}
						{% else %}
						<span class="badge" id="notification-badge">
							0
						</span>
						{% endif %}
					</a>
				{% else  %}
					<a class="nav-link" href="{% url 'user_requests:show-complaint-requests' %}">
						<i class="fa fa-solid fa-newspaper"></i>
						Complaint Requests
						{% if request.user.is_authenticated %}
						{% if not request.user.user_notifications %}
						<span class="badge" id="notification-badge">
							0
						</span>
						{% else %}
						<span class="badge notification-badge-animation" id="notification-badge">
							{{request.user.user_notifications}}
						</span>
						{% endif %}
						{% else %}
						<span class="badge" id="notification-badge">
							0
						</span>
						{% endif %}
					</a>
				{% endif %}
			</li>
			{% if request.user.is_authenticated %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'accounts:profile-view' request.user.slug %}"><i class="fa fa-solid fa-user"></i>Profile</a>
			</li>
			{% else %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'accounts:profile-view' request.user %}"><i class="fa fa-solid fa-user"></i>Profile</a>
			</li>
			{% endif %}
		</ul>
	</div>
</nav>

<!-- TEMPLATE_CONTEXT_PROCESSORS = (
	"django.core.context_processors.auth", 
	"django.core.context_processors.debug", 
	"django.core.context_processors.i18n", 
	"django.core.context_processors.media", 
	'django.core.context_processors.request',
) -->

<script>
  // ---------Responsive-navbar-active-animation-----------
function test(){
	var tabsNewAnim = $('#navbarSupportedContent');
	var selectorNewAnim = $('#navbarSupportedContent').find('li').length;
	var activeItemNewAnim = tabsNewAnim.find('.active');
	var activeWidthNewAnimHeight = activeItemNewAnim.innerHeight();
	var activeWidthNewAnimWidth = activeItemNewAnim.innerWidth();
	var itemPosNewAnimTop = activeItemNewAnim.position();
	var itemPosNewAnimLeft = activeItemNewAnim.position();
	$(".hori-selector").css({
		"top":itemPosNewAnimTop.top + "px", 
		"left":itemPosNewAnimLeft.left + "px",
		"height": activeWidthNewAnimHeight + "px",
		"width": activeWidthNewAnimWidth + "px"
	});
	$("#navbarSupportedContent").on("click","li",function(e){
		$('#navbarSupportedContent ul li').removeClass("active");
		$(this).addClass('active');
		var activeWidthNewAnimHeight = $(this).innerHeight();
		var activeWidthNewAnimWidth = $(this).innerWidth();
		var itemPosNewAnimTop = $(this).position();
		var itemPosNewAnimLeft = $(this).position();
		$(".hori-selector").css({
			"top":itemPosNewAnimTop.top + "px", 
			"left":itemPosNewAnimLeft.left + "px",
			"height": activeWidthNewAnimHeight + "px",
			"width": activeWidthNewAnimWidth + "px"
		});
	});
}
$(document).ready(function(){
	setTimeout(function(){ test(); });
});
$(window).on('resize', function(){
	setTimeout(function(){ test(); }, 500);
});
$(".navbar-toggler").click(function(){
	$(".navbar-collapse").slideToggle(300);
	setTimeout(function(){ test(); });
});



// --------------add active class-on another-page move----------
jQuery(document).ready(function($){
	// Get current path and find target link
	var path = window.location.pathname.split("/").pop();
	var target = $('#navbarSupportedContent ul li a[href="'+path+'"]');
	var header = document.getElementById("navbar-menu");
	var btns = header.getElementsByClassName("nav-item");
	var window_link_list = window.location.href.split('/');
	if(window_link_list.length === 5 && window_link_list[3] === "complaints") {
		btns[0].className += " active";
	}
	else if(window_link_list[3] === "profile") {
		btns[4].className += " active";
	}
	else if(window_link_list.length === 4 && window_link_list[3] === "complaints") {
		btns[0].className += " active";
	}
	else if(window_link_list.length === 6 && window_link_list[3] === "complaints" && window_link_list[4] === "request-history") {
		btns[1].className += " active";
	}
	else if(window_link_list.length === 6 && window_link_list[3] === "complaints" && window_link_list[4] !== "create-complaint") {
		btns[0].className += " active";
	}
	else if(window_link_list.length === 6 && window_link_list[3] === "complaints" && window_link_list[4] === "create-complaint") {
		btns[2].className += " active";
	}
	else if(window_link_list.length === 5 && window_link_list[3] === "show-complaint-requests") {
		btns[3].className += " active";
	}
	else if(window_link_list.length === 5 && window_link_list[3] === "show-contact-requests") {
		btns[3].className += " active";
	}
	else if(window_link_list.length === 6 && window_link_list[4] === "request-history") {
		btns[3].className += " active";
	}
	else {
		btns[0].className += " active";
	}
});
</script>

{{ room_name|json_script:"room-name" }}

{% if request.user.is_authenticated %}

<script>
	const roomName = "notification_requests_for_"+"{{request.user}}";
	const notificationSocket = new WebSocket(
	'ws://127.0.0.1:8000/ws/notification/'
	+ roomName
	+ '/'
	);

  notificationSocket.onmessage = function(e) {
    const data = JSON.parse(e.data);
    //document.querySelector('#chat-log').value += (data.message + '\n');
    // alert(parseInt(document.getElementById("notification-badge").innerHTML));
    document.getElementById("notification-badge").innerHTML = parseInt(document.getElementById("notification-badge").innerHTML) + 1;
	$("#notification-badge").addClass("notification-badge-animation");
  };
</script>

{% endif %}

DV_prevention/accounts/templates/accounts/status.html
<br>
<div class="row" style="min-width: 100%;">
  <div class="col-md">
    <div class="card text-center text-white mb-3" id="total-orders">
        <div class="card-header">
          <h5 class="card-title">Complaints Solved</h5>
        </div>
        <div class="card-body">
          <h3 class="card-title">0</h3>
        </div>
    </div>
  </div>

  <div class="col-md">
    <div class="card text-center text-white mb-3" id="orders-delivered">
        <div class="card-header">
          <h5 class="card-title">Verified by</h5>
        </div>
        <div class="card-body">
          <h3 class="card-title verified-count-{{profile.id}}">{{verifications_count}}</h3>
        </div>
    </div>
    {% if request.user.id != profile.id %}
    <button class="btn btn-success verified-count" data-profile="{{profile.id}}">+</button>
    {% endif %}
  </div>

  <div class="col-md">
    <div class="card text-center text-white mb-3" id="total-orders">
        <div class="card-header">
          <h5 class="card-title">Reported by</h5>
        </div>
        <div class="card-body">
          <h3 class="card-title">0</h3>
        </div>
        {% if request.user.id != profile.id %}
        <button class="btn btn-danger reported-count" data-profile="{{profile.id}}">+</button>
        {% endif %}
    </div>
  </div>
</div>

<script>
  $('.verified-count').on('click', function() {
    var profile_id = $(this).data('profile');
    $.ajax({
      url: "{% url 'user_requests:verify-user' profile.id%}",
      type: "post",
      data: {
        profile_id: profile_id,
        csrfmiddlewaretoken: "{{csrf_token}}",
      },
      dataType: 'json',
      success: function(response) {
        var previous_verified_count = $('.verified-count-'+profile_id).text();
        console.log(previous_verified_count);
        if(response['verification_post'] == true) {
          $('.verified-count-'+profile_id).text(parseInt(previous_verified_count)+1);
        }
      }
    });
  });
  $('.reported-count').on('click', function() {
    var profile_id = $(this).data('profile');
    $.ajax({
      url: "{% url 'user_requests:report-user' profile.id%}",
      type: "post",
      data: {
        profile_id: profile_id,
        csrfmiddlewaretoken: "{{csrf_token}}",
      },
      dataType: 'json',
      success: function(response) {
        var previous_reported_count = $('.reported-count-'+profile_id).text();
        console.log(previous_reported_count);
        if(response['report_post'] == true) {
          $('.reported-count-'+profile_id).text(parseInt(previous_reported_count)+1);
        }
      }
    });
  });
</script>