DV_prevention/DV_prevention/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('user_auth.urls', 'user_auth'), namespace='user_auth')),
    path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include(('user_requests.urls', 'user_requests'), namespace='user_requests')),
    path('complaints/', include(('complaints.urls', 'complaints'), namespace='complaints')),
]

DV_prevention/accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'accounts'

urlpatterns = [
	path('profile/<str:profile_slug>/', views.profileView, name = 'profile-view'),
	path('profile-file-drop/', views.profile_drop_zone_file, name = 'profile-file-drop-zone-view'),
	path('profile-file-drop/upload/', views.profile_file_upload_view, name = 'profile-file-drop-upload-upload-view'),
	path('edit-profile/', views.profileEdit, name = 'profile-edit'),
	path('profile-rate/<str:profile_slug>/', views.profileRate, name='profile-rate'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,
	document_root = settings.MEDIA_ROOT)

DV_prevention/complaints/urls.py
from django.urls import path
from . import views
app_name = 'complaints'

urlpatterns = [
	path('', views.exploreComplaints, name='explore-complaints'),
	path('tag/#<str:complaint_tag>/', views.exploreComplaintsByTag, name='explore-complaints-by-tag'),
	path('request-history/', views.requestHistory, name = 'request-history'),
	path('find-nearest-helpers/', views.findNearestActivist, name='complaint-request-nearest-activist'),
	path('complaint-file-drop/', views.complaint_drop_zone_file, name = 'complaint-file-drop-zone-view'),
	path('complaint-file-drop/upload/', views.complaint_file_upload_view, name = 'complaint-file-drop-upload-upload-view'),
	path('investigate/<str:complaint_id>/', views.investigateComplaint, name='investigate-complaint'),
	path('mark-as-done/<str:complaint_id>/', views.markComplaintAsDone, name='mark-as-done'),
	path('create-complaint/', views.createComplaint, name='create-complaint'),
	path('delete_complaint/<str:complaint_id>/', views.deleteComplaint, name='delete-complaint'),
	path('<str:complaint_id>/', views.showComplaintDetail, name='show-complaint-detail'),
	path('<str:complaint_id>/<str:message_type>/', views.addMessage, name='update-complaint'),
	path('<str:complaint_id>/vote_change/upvote/', views.complaintUpvote, name='upvote-complaint'),
	path('<str:complaint_id>/vote_change/downvote/', views.complaintDownvote, name='downvote-complaint'),
	path('<str:complaint_id>/<str:message_type>/', views.addMessage, name='update-complaint'),
]

DV_prevention/complaints/models.py
from django.db import models
from accounts.models import User
from taggit.managers import TaggableManager

# Create your models here.
class Complaint(models.Model):
	complaint_title = 					models.CharField(max_length = 1000, null = True)
	complaint_filer = 					models.ForeignKey(User, null = True, on_delete = models.CASCADE)
	complaint_description = 			models.TextField(null = True)
	complaint_status = 					models.CharField(max_length = 10, default = 'active')
	complaint_request_image = 			models.ImageField(null = True, blank = True, upload_to = 'complaints', default = 'complaints/default-image.jpg')
	complaint_place = 					models.CharField(max_length = 1000, null = True, blank = True)
	complaint_under_investigation_by = 	models.CharField(max_length = 1000, null = True, blank = True)
	complaint_upvotes = 				models.IntegerField(default = 0)
	complaint_upvotes_users = 			models.TextField(default=',', blank = True)
	complaint_downvotes_users = 		models.TextField(default=',', blank = True)
	complaint_place_geocode = 			models.JSONField(null = True, blank = True)
	tags = TaggableManager()

	def __str__(self):
		return self.complaint_title

class Complaint_Document(models.Model):
	complaint_name = 			models.ForeignKey(Complaint, null = True, on_delete = models.CASCADE, related_name = 'complaint_documents')
	complaint_file = 			models.ImageField(null = True, upload_to = 'identity')
	
	def __str__(self):
		return str(self.complaint_file)

class Message(models.Model):
	message_user = 			models.ForeignKey(User, null = True, on_delete = models.CASCADE)
	message_complaint = 	models.ForeignKey(Complaint, null = True, on_delete = models.CASCADE)
	message_type = 			models.CharField(max_length = 50, default = "comment")
	message_content = 		models.CharField(max_length = 1000, null = True)

	def __str__(self):
		return str(self.message_user) + " message on " + str(self.message_complaint)

class Investigation(models.Model):
	investigation_complaint =		models.ForeignKey(Complaint, null = True, on_delete = models.CASCADE)
	investigation_in_charge = 		models.ForeignKey(User, null = True, on_delete = models.CASCADE)

	def __str__(self):
		return str(self.investigation_complaint) + " by " + str(self.investigation_in_charge)

class TagComplaint(models.Model):
	tag = 				models.CharField(max_length = 1000, null = True)
	tag_complaints = 	models.JSONField(null = True)

	def __str__(self):
		return self.tag

	def save(self, *args, **kwargs):
		if(self.tag_complaints == None):
			self.tag_complaints = {'complaints': []}
		super(TagComplaint, self).save(*args, **kwargs)

DV_prevention/complaints/forms.py
from django.forms import ModelForm
from .models import Complaint
import json

class ComplaintForm(ModelForm):
	class Meta:
		model = Complaint
		fields = ['complaint_title', 'complaint_description', 'complaint_place', 'complaint_request_image', 'complaint_place_geocode', 'tags']

	def save(self, commit=True):
		instance = super(ComplaintForm, self).save(commit=False)
		instance.complaint_place = instance.complaint_place_geocode['place_name']
		# instance.flag1 = 'flag1' in self.cleaned_data['multi_choice'] # etc
		if commit:
			instance.save()
		return instance

DV_prevention/complaints/views.py
from .forms import ComplaintForm
from .models import *
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from user_auth.decorators import auth_or_not
from accounts.models import User
from user_requests.models import Complaint_Request
from PIL import Image
from taggit.models import Tag
import random
from django.shortcuts import render, get_object_or_404
import json

# Create your views here.

@login_required(login_url='user-auth:login')
@auth_or_not(1)
def findNearestActivist(request):
	"""
	Pass Complaint and user in context, then find 
	nearest activists from the complaint
	"""
	# complaint = Complaint.objects.get(complaint_filer = request.user)
	users = User.objects.all().exclude(username = request.user).exclude(user_place_geocode = None)
	complaint = Complaint.objects.get(complaint_filer = request.user)
	context = {'users': users, 'complaint': complaint}
	return render(request, 'complaints/nearest_activist_map.html', context)

#Helper Functions
def complaint_detail_components(request, complaint_id):
	"""
	Helper Function, returns components regularly needed in context
	"""
	complaint = Complaint.objects.get(id = complaint_id)
	profile = complaint.complaint_filer
	updates = Message.objects.filter(message_type = "update", message_complaint = complaint)
	comments = Message.objects.filter(message_type = "comment", message_complaint = complaint)
	total_updates = len(updates)
	total_comments = len(comments)
	investigations = Investigation.objects.filter(investigation_complaint = complaint)
	investigastion_ongoing_by_curr_user = False
	if(str(request.user) != "AnonymousUser"):
		investigastion_ongoing_by_curr_user = investigations.filter(investigation_in_charge = request.user).exists()
	complaint_documents = Complaint_Document.objects.filter(complaint_name = complaint)
	complaint_json = complaint.complaint_place_geocode

	return {'complaint':complaint, 'updates':updates, 'comments':comments, 'total_updates':total_updates, 
	'total_comments':total_comments, 'current_complaint_link':"http://127.0.0.1:8000/complaints/"+str(complaint.id), 
	'investigations':investigations, 
	'investigastion_ongoing_by_curr_user': investigastion_ongoing_by_curr_user, 'profile':profile, 
	'complaint_documents':complaint_documents, 'complaint_json': complaint_json}

def exploreComplaints(request, sorting_parameter="upvotes"):
	"""
	See availible complaints, shown on user login
	"""
	# request.session['notifications_for_request_user'] += 1
	# print(request.session['notifications_for_request_user'])
	complaints = Complaint.objects.filter(complaint_status='active')
	if(sorting_parameter=="name"):
		complaints = sorted(complaints, key = lambda x : x.complaint_name, reverse = True)
	else:
		complaints = sorted(complaints, key = lambda x : x.complaint_upvotes, reverse = True)
	context = {'complaints':complaints, 'complaint_page_title': 'Complaints'}
	return render(request, 'complaints/complaints.html', context)

def exploreComplaintsByTag(request, complaint_tag):
	"""
	See availible complaints, shown on user login
	"""
	tag = TagComplaint.objects.get(tag = complaint_tag)
	complaints = []
	for i in tag.tag_complaints['complaints']:
		try:
			complaint = Complaint.objects.get(complaint_title = i, complaint_status = "active")
			complaints.append(complaint)
		except:
			pass
	
	context = {'complaints':complaints, 'complaint_page_title': 'Complaints with tag #'+tag.tag, 'filtered_tag': str(tag)}
	return render(request, 'complaints/complaints.html', context)

def showComplaintDetail(request, complaint_id):
	"""
	Show detail of a particular complaint
	"""
	context = complaint_detail_components(request, complaint_id)
	return render(request, 'complaints/complaint_detail.html', context)

@login_required(login_url='user-auth:login')
@auth_or_not(1)
def createComplaint(request):
	"""
	Create a Complaint
	"""
	user = request.user
	if request.method == "POST":
		form = ComplaintForm(request.POST, request.FILES)
		if form.is_valid():
			# Delete all existing complaints of the user
			Complaint.objects.filter(complaint_filer = user).delete()
			newpost = form.save(commit=False)
			newpost.save()
			# Without this next line the tags won't be saved.
			form.save_m2m()
			complaint = Complaint.objects.filter(complaint_filer = None, complaint_status="active")
			complaint.update(complaint_filer = user)
			
			complaint = Complaint.objects.get(complaint_filer = user)
			for complaint_tag in complaint.tags.all():
				tag = TagComplaint.objects.get_or_create(tag = str(complaint_tag))
				tag[0].tag_complaints['complaints'].append(str(complaint.complaint_title))
				tag[0].save()
			# Complaint.objects.filter(user=None, status='active').update(user=user)
		else:
			print(form.errors)
		return redirect('complaints:explore-complaints')
	
	form = ComplaintForm()
	context = {'form':form}
	return render(request, 'complaints/create_complaint_page.html', context)

@login_required(login_url='user-auth:login')
@auth_or_not(1)
def addMessage(request, complaint_id, message_type):
	"""
	Add comment/update to complaint
	"""
	if request.method == "POST":
		message_content = None
		complaint = Complaint.objects.get(id = complaint_id)
		if message_type == "update":
			message_content = request.POST.get('update-add')
		else:
			message_content = request.POST.get('comment-add')

		if len(message_content) == 0:
			context = complaint_detail_components(request, complaint_id)
			return render(request, 'complaints/complaint_detail.html', context)
		Message.objects.create(message_user = request.user, message_complaint = complaint, 
		message_type = message_type, message_content = message_content)

	return redirect(reverse('complaints:show-complaint-detail', kwargs={'complaint_id': complaint_id}))

@login_required(login_url='user-auth:login')
@auth_or_not(1)
def investigateComplaint(request, complaint_id):
	complaint = Complaint.objects.get(id = complaint_id)
	if(not Investigation.objects.filter(investigation_complaint = complaint, investigation_in_charge = request.user).exists()):
		Investigation.objects.create(investigation_complaint = complaint, investigation_in_charge = request.user)
	if(Complaint_Request.objects.filter(requested_complaint = complaint, requested_by = complaint.complaint_filer, 
	requested_user = request.user).exists()):
		Complaint_Request.objects.filter(requested_complaint = complaint, 
		requested_by = complaint.complaint_filer, requested_user = request.user).delete()
	return JsonResponse({'post':True})

@login_required(login_url='user-auth:login')
@auth_or_not(1)
def complaintUpvote(request, complaint_id):
	complaint = Complaint.objects.get(id = complaint_id)
	complaint_upvotes_list = complaint.complaint_upvotes_users.split(',')
	for i in complaint_upvotes_list:
		if(i == str(request.user)):
			return JsonResponse({'upvote_post':False})
	complaint.complaint_upvotes += 1
	complaint.complaint_upvotes_users += (str(request.user)+',')
	complaint.save()
	return JsonResponse({'upvote_post':True})

@login_required(login_url='user-auth:login')
@auth_or_not(1)
def complaintDownvote(request, complaint_id):
	complaint = Complaint.objects.get(id = complaint_id)
	complaint_downvotes_list = complaint.complaint_downvotes_users.split(',')
	for i in complaint_downvotes_list:
		if(i == str(request.user)):
			return JsonResponse({'upvote_post':False})
	complaint.complaint_upvotes -= 1
	complaint.complaint_downvotes_users += (str(request.user)+',')
	complaint.save()
	return JsonResponse({'downvote_post':True})

@login_required(login_url='user_auth:login')
@auth_or_not(1)
def complaint_drop_zone_file(request):
	context = {}
	return render(request, 'complaints/complaint_drop_zone.html', context)

@login_required(login_url='user_auth:login')
@auth_or_not(1)
def complaint_file_upload_view(request):
	"""
	Upload Verification files
	"""
	complaint = Complaint.objects.filter(complaint_filer = request.user)[0]
	if request.method == "POST":
		my_file = request.FILES.get('file')
		if(str(my_file).endswith('jpg') or str(my_file).endswith('jpeg') or str(my_file).endswith('jfif') or str(my_file).endswith('pjpeg') or str(my_file).endswith('pjp') or str(my_file).endswith('png')):
			complaint_document = Complaint_Document.objects.create(complaint_name = complaint, complaint_file = my_file)
		else:
			pass
		return redirect('/')
	return JsonResponse({'post':'false'})

@login_required(login_url='user-auth:login')
@auth_or_not(1)
def requestHistory(request):
	if(not Complaint.objects.filter(complaint_filer = request.user).exists()):
		return render(request, 'complaints/no_complaint.html')
	complaint = Complaint.objects.get(complaint_filer = request.user)
	return redirect(reverse('complaints:show-complaint-detail', kwargs={'complaint_id': complaint.id}))

@login_required(login_url='user-auth:login')
@auth_or_not(1)
def markComplaintAsDone(request, complaint_id):
	for i, j in zip(request.POST.items(), range(len(request.POST))):
		if j == 0:
			continue
		activist = User.objects.get(username=i[1])
		activist.user_complaints_solved += 1
		activist.save()
	Complaint.objects.get(id = complaint_id).delete()
	return redirect('complaints:explore-complaints')

@login_required(login_url='user-auth:login')
@auth_or_not(1)
def deleteComplaint(request, complaint_id):
	Complaint.objects.get(id = complaint_id).delete()
	return redirect('complaints:explore-complaints')

DV_prevention/complaints/templates/complaints/complaint_drop_zone.html
{% extends 'accounts/main.html' %}

{% block content %}
<form action="upload/" class="dropzone" method="POST" id="myGreatDropzone">
    {% csrf_token %}
    <div class="fallback">
        <input name="file" type="file" multiple/>
    </div>
</form>

<button type="submit" id="button" class="btn btn-primary mt-5" style="margin: auto; 
background-color: #AC3B61; color: #EDC7B7; display: block; width: 50%;">Submit</button>

<script>
Dropzone.options.myGreatDropzone = { // camelized version of the `id`
    autoProcessQueue: false,
    maxFilesize: 25, // MB
    init: function () {
        var myDropzone = this;

        // Update selector to match your button
        $("#button").click(function (e) {
            e.preventDefault();
            myDropzone.processQueue();
        });

        this.on('sending', function(file, xhr, formData) {
            // Append all form inputs to the formData Dropzone will POST
            var data = $('#myGreatDropzone').serializeArray();
            $.each(data, function(key, el) {
                formData.append(el.name, el.value);
            });
        });
    }
};
</script>

{% endblock %}

DV_prevention/complaints/templates/complaints/complaints.html
{% load static %}
{% include 'accounts/main.html' %}

{% block content %}

<style>
	* {
		box-sizing: border-box;
	}
 .blog-card {
	display: flex;
	flex-direction: column;
	margin: 1rem auto;
	box-shadow: 0 3px 7px -1px black;
	margin-bottom: 1.6%;
	background-color: #EDC7B7;
	line-height: 1.4;
	font-family: sans-serif;
	border-radius: 5px;
	overflow: hidden;
	z-index: 0;
}
 .blog-card a {
	color: inherit;
}
 .blog-card a:hover {
	color: #5ad67d;
}
 .blog-card:hover .photo {
	transform: scale(1.3) rotate(3deg);
}
 .blog-card .meta {
	position: relative;
	z-index: 0;
	height: 200px;
}
 .blog-card .photo {
	position: absolute;
	top: 0;
	right: 0;
	bottom: 0;
	left: 0;
	background-size: cover;
	background-position: center;
	transition: transform 0.2s;
}
 .blog-card .details, .blog-card .details ul {
	margin: auto;
	padding: 0;
	list-style: none;
}
 .blog-card .details {
	position: absolute;
	top: 0;
	bottom: 0;
	left: -100%;
	margin: auto;
	transition: left 0.2s;
	background: rgba(0, 0, 0, .6);
	color: #fff;
	padding: 10px;
	width: 100%;
	font-size: 0.9rem;
}
 .blog-card .details a {
	 text-decoration: dotted underline;
}
 .blog-card .details ul li {
	 display: inline-block;
}
 .blog-card .details .author:before {
	 font-family: FontAwesome;
	 margin-right: 10px;
	 content: "\f007";
}
 .blog-card .details .date:before {
	 font-family: FontAwesome;
	 margin-right: 10px;
	 content: "\f133";
}
 .blog-card .details .tags ul:before {
	 font-family: FontAwesome;
	 content: "\f02b";
	 margin-right: 10px;
}
 .blog-card .details .tags li {
	 margin-right: 2px;
}
 .blog-card .details .tags li:first-child {
	 margin-left: -4px;
}
 .blog-card .description {
	 padding: 1rem;
	 background-color: #EDC7B7;
	position: relative;
	 z-index: 1;
}
 .blog-card .description h1, .blog-card .description h2 {
	 font-family: Poppins, sans-serif;
}
 .blog-card .description h1 {
	 line-height: 1;
	 margin: 0;
	 font-size: 1.7rem;
}
 .blog-card .description h2 {
	 font-size: 1rem;
	 font-weight: 300;
	 text-transform: uppercase;
	 color: black;
	 margin-top: 5px;
}
 .blog-card .description .read-more {
	 text-align: right;
}
 .blog-card .description .read-more a {
	 color: #5ad67d;
	 display: inline-block;
	 position: relative;
}
 .blog-card .description .read-more a:after {
	 content: "\f061";
	 font-family: FontAwesome;
	 margin-left: -10px;
	 opacity: 0;
	 vertical-align: middle;
	 transition: margin 0.3s, opacity 0.3s;
}
 .blog-card .description .read-more a:hover:after {
	 margin-left: 5px;
	 opacity: 1;
}
 .blog-card p {
	 position: relative;
	 margin: 1rem 0 0;
}
 .blog-card p:first-of-type {
	 margin-top: 1.25rem;
}
 .blog-card p:first-of-type:before {
	 content: "";
	 position: absolute;
	 height: 5px;
	 background: #5ad67d;
	 width: 35px;
	 top: -0.75rem;
	 border-radius: 3px;
}
 .blog-card:hover .details {
	 left: 0%;
}
 @media (min-width: 640px) {
	 .blog-card {
		 flex-direction: row;
		 max-width: 700px;
	}
	 .blog-card .meta {
		 flex-basis: 40%;
		 height: auto;
	}
	 .blog-card .description {
		 flex-basis: 60%;
	}
	 .blog-card .description:before {
		 transform: skewX(-3deg);
		 content: "";
		 background: #fff;
		 width: 30px;
		 position: absolute;
		 left: -10px;
		 top: 0;
		 bottom: 0;
		 z-index: -1;
	}
	 .blog-card.alt {
		 flex-direction: row-reverse;
	}
	 .blog-card.alt .description:before {
		 left: inherit;
		 right: -10px;
		 transform: skew(3deg);
	}
	 .blog-card.alt .details {
		 padding-left: 25px;
	}
}
 
</style>

<style>
	@import url('https://fonts.googleapis.com/css?family=Dosis:300,400,500,600,700,800|Quicksand:300,400,500,700');

html, body{ font-family: 'Quicksand', sans-serif;}
a, a:hover,a:active, a:focus{ text-decoration: none !important; outline: none !important; box-shadow: none; }

/*blog-area*/
.blogs-item {width: calc(100%/3 - 30px);float: left;margin: 0 15px; transition: all 0.25s}
.blogs:after {content: '';display: block;clear: both;}
.blog-img .blog-time .blog-month {font-size: 12px;line-height: normal;letter-spacing: 0.5px; font-weight: 500;}
.blog-img .blog-time .blog-date {font-size: 22px;line-height: normal;font-weight: 600;}
.blog-img .blog-time {position: absolute;height: 50px;width: 50px; background-color: #123C69; color: #EDC7B7; top: 10px;left: 10px;text-align: center;color: #fff;text-transform: uppercase;line-height: normal;margin: 0;}
.blog-img {position: relative;}
.blog-detail{padding: 20px 25px;border: 1px solid #EDC7B7; background-color: #EDC7B7; position: relative;overflow: hidden;-webkit-transition: border .4s;-moz-transition: border .4s;-ms-transition: border .4s;transition: border .4s; z-index: 0;}
.blogs-item:hover .blog-detail:after {left: 0;bottom: 0;-webkit-transform: scale(15) translateZ(0);-moz-transform: scale(15) translateZ(0);-ms-transform: scale(15) translateZ(0);-o-transform: scale(15) translateZ(0);transform: scale(15) translateZ(0);}
.blog-detail h4 a {color: #AC3B61;}
.blog-detail h4 {font-size: 18px;line-height: 30px;text-transform: capitalize;font-weight: 500; margin: 0;}
.blog-detail ul li a {color: #676767;}
.blog-detail ul li {font-size: 11px;line-height: 12px;text-transform: uppercase;border-right: 1px solid #e0e0e0;padding-right: 10px;display: inline-block;}
.blog-detail ul {list-style: none;padding: 0;}
.blog-detail ul li:last-child {border: 0; padding-right: 0;}
.blog-detail p {line-height: 25px;font-size: 16px;letter-spacing: .5px;color: #878787;margin: 0;}
.blogs-item .blog-img img {filter: grayscale(0);}
.blogs-item:hover .blog-img img {filter: grayscale(1);}
.blogs {padding: 20px 0;}
.blog-area {padding: 30px 0;}
.read-more-btn a {padding: 10px 25px;display: inline-block;color: #666;border: 1px solid #666;letter-spacing: 1px;text-transform: uppercase;font-weight: 500;box-shadow: 0 3px 0 transparent;transition: 0.3s ease;}
.read-more-btn a:hover {background: #5745ae;border-color: #5745ae;color: #fff;box-shadow: 0 3px 0 #3c377b;}
.read-more-btn {text-align: center;padding: 30px 0 10px;}
.blog-img img{ max-width:100%; height:auto;}
/*end*/
.heading h2 {position: relative;font-weight: 600;font-family: 'Dosis', sans-serif;text-transform: uppercase;padding: 0 0 10px;color: #AC3B61;}
.heading h2:before {position: absolute;content: '';height: 1px;width: 150px;background: #EDC7B7; left: 0;right: 0;bottom: 1px;margin: auto;}
.heading h2:after {content: '';height: 3px;width: 50px;background: #AC3B61;position: absolute;left: 0;right: 0;margin: auto;bottom: 0;}
.heading p {color: black;}
.heading {text-align: center;padding: 20px 0;max-width: 750px;margin: 0 auto;}
/*hover*/
.hvr-float-shadow {
    display: inline-block;
    vertical-align: middle;
    -webkit-transform: perspective(1px) translateZ(0);
    transform: perspective(1px) translateZ(0);
    box-shadow: 0 0 1px transparent;
    position: relative;
    -webkit-transition-duration: .3s;
    transition-duration: .3s;
    -webkit-transition-property: transform;
    transition-property: transform;
}
.hvr-float-shadow:active, .hvr-float-shadow:focus, .hvr-float-shadow:hover {
    -webkit-transform: translateY(-5px);
    transform: translateY(-5px);
}

.hvr-float-shadow:before {
    pointer-events: none;
    position: absolute;
    z-index: -1;
    content: '';
    top: 100%;
    left: 5%;
    height: 10px;
    width: 90%;
    opacity: 0;
    background: -webkit-radial-gradient(center,ellipse,rgba(0,0,0,.35) 0,transparent 80%);
    background: radial-gradient(ellipse at center,rgba(0,0,0,.35) 0,transparent 80%);
    -webkit-transition-duration: .3s;
    transition-duration: .3s;
    -webkit-transition-property: transform,opacity;
    transition-property: transform,opacity;
}

.hvr-float-shadow:active:before, .hvr-float-shadow:focus:before, .hvr-float-shadow:hover:before {
    opacity: 1;
    -webkit-transform: translateY(5px);
    transform: translateY(5px);
}

/*media*/

@media (max-width:991px){
    .blogs-item {width: calc(100%/2 - 30px);margin: 0 15px 30px;}
}


@media (max-width:767px){
    .blogs-item {width: 100%;margin: 0 auto 30px;max-width: 470px;display: block;float: none;}
    .read-more-btn {padding: 0 0 10px;}
}

@media (max-width:400px){
    .blog-detail {padding:20px;}
}

.example::-webkit-scrollbar {
  display: none;
}

/* Hide scrollbar for IE, Edge and Firefox */
.scrolling-wrapper {
  -ms-overflow-style: none;  /* IE and Edge */
  scrollbar-width: none;  /* Firefox */
}

#cropped-description {
  overflow:hidden; height: 200px; text-overflow:ellipsis;
}

#cropped-tags {
  overflow:hidden; 
  white-space:nowrap; 
  text-overflow:ellipsis;
}

</style>

<div class="container mt-5 mb-5">
  <section class="blog-area">
    <div class="container">
      <div class="heading" style="color: #AC3B61">
		<h2>{{complaint_page_title}}</h2>
      </div>
      <div class="blogs">
        <div class="row">
		{% for complaint in complaints %}
          <div class="blogs-item hvr-float-shadow wow fadeInLeft h-100 mb-5" data-wow-delay="0.5s">
            <div class="blog-img photo">
              <a href="{% url 'complaints:show-complaint-detail' complaint.id %}"><img src="{% static 'images/' %}{{complaint.complaint_request_image}}" alt="" class="img-fluid" style="height: 200px; width: 100%;"></a>
              <p class="blog-time">
              <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
              <span class="blog-date"><i class="fa fa-solid fa-chevron-up"></i></span>
              <br>
              <span class="blog-month">{{complaint.complaint_upvotes}}</span>
              </p>
            </div>
            <div class="blog-detail">
              <h4><a href="javascript:;">{{complaint.complaint_title}}</a></h4>
              <ul class="scrolling-wrapper" id="cropped-tags">
                {% for tag in complaint.tags.all %}
				{% if filtered_tag == tag|slugify %}
					<li style="background-color: yellow; padding: 5px;"><a href="{% url 'complaints:explore-complaints-by-tag' tag %}">#{{tag}}</a></li>
				{% else %}
					<li><a href="{% url 'complaints:explore-complaints-by-tag' tag %}">#{{ tag }}</a></li>
				{% endif %}
                {% endfor %}
              </ul>
              <p class="scrolling-wrapper" id="cropped-description">{{complaint.complaint_description}}</p>...
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </section>
</div>

{% endblock %}

<!--<div class="read-more-btn">
            <a href="javascript:;" class="hvr-float-shadow">Read More</a>
        </div>-->

DV_prevention/complaints/templates/complaints/no_complaint.html
{% load static %}
{% include 'accounts/main.html' %}

{% block content %}
{% endblock %}