DV_prevention/DV_prevention/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('user_auth.urls', 'user_auth'), namespace='user_auth')),
    path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include(('user_requests.urls', 'user_requests'), namespace='user_requests')),
    path('complaints/', include(('complaints.urls', 'complaints'), namespace='complaints')),
]

DV_prevention/accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'accounts'

urlpatterns = [
	path('profile/<str:profile_slug>/', views.profileView, name = 'profile-view'),
	path('profile-file-drop/', views.profile_drop_zone_file, name = 'profile-file-drop-zone-view'),
	path('profile-file-drop/upload/', views.profile_file_upload_view, name = 'profile-file-drop-upload-upload-view'),
	path('edit-profile/', views.profileEdit, name = 'profile-edit'),
	path('profile-rate/<str:profile_slug>/', views.profileRate, name='profile-rate'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,
	document_root = settings.MEDIA_ROOT)

DV_prevention/complaints/urls.py
from django.urls import path
from . import views
app_name = 'complaints'

urlpatterns = [
	path('', views.exploreComplaints, name='explore-complaints'),
	path('tag/#<str:complaint_tag>/', views.exploreComplaintsByTag, name='explore-complaints-by-tag'),
	path('request-history/', views.requestHistory, name = 'request-history'),
	path('find-nearest-helpers/', views.findNearestActivist, name='complaint-request-nearest-activist'),
	path('complaint-file-drop/', views.complaint_drop_zone_file, name = 'complaint-file-drop-zone-view'),
	path('complaint-file-drop/upload/', views.complaint_file_upload_view, name = 'complaint-file-drop-upload-upload-view'),
	path('investigate/<str:complaint_id>/', views.investigateComplaint, name='investigate-complaint'),
	path('mark-as-done/<str:complaint_id>/', views.markComplaintAsDone, name='mark-as-done'),
	path('create-complaint/', views.createComplaint, name='create-complaint'),
	path('delete_complaint/<str:complaint_id>/', views.deleteComplaint, name='delete-complaint'),
	path('<str:complaint_id>/', views.showComplaintDetail, name='show-complaint-detail'),
	path('<str:complaint_id>/<str:message_type>/', views.addMessage, name='update-complaint'),
	path('<str:complaint_id>/vote_change/upvote/', views.complaintUpvote, name='upvote-complaint'),
	path('<str:complaint_id>/vote_change/downvote/', views.complaintDownvote, name='downvote-complaint'),
	path('<str:complaint_id>/<str:message_type>/', views.addMessage, name='update-complaint'),
]

DV_prevention/user_requests/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'user_requests'

urlpatterns = [
	path('verify-user/<str:profile_id>/', views.verifyUser,name = 'verify-user'),
	path('report-user/<str:profile_id>/', views.reportUser,name = 'report-user'),
	path('request-contact-info/<str:profile_id>/', views.requestContactInfo,name = 'request-contact-info'),
	path('show-contact-requests/', views.showContactRequests, name = 'show-contact-requests'),
	path('show-complaint-requests/', views.showComplaintRequests, name = 'show-complaint-requests'),
	path('contact-request-action/<str:request_id>/<int:action>/', views.requestContactInfoAction, name = 'request-contact-info-action'),
	path('complaint-request-action/<str:profile_id>/', views.requestComplaintAction, name = 'request-complaint-action'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,
	document_root = settings.MEDIA_ROOT)

DV_prevention/user_requests/models.py
from django.db import models
from accounts.models import User
from complaints.models import Complaint

# Create your models here.

class Verification(models.Model):
	verified_user = 	models.ForeignKey(User, null = True, on_delete = models.CASCADE, related_name = 'verified_user')
	verified_by = 		models.ForeignKey(User, null = True, on_delete = models.CASCADE, related_name = 'verified_by')

	def __str__(self):
		return str(self.verified_user) + ' verified by ' + str(self.verified_by)

class Report(models.Model):
	reported_user = 	models.ForeignKey(User, null = True, on_delete = models.CASCADE, related_name = 'reported_user')
	reported_by = 		models.ForeignKey(User, null = True, on_delete = models.CASCADE, related_name = 'reported_by')

	def __str__(self):
		return str(self.reported_user) + ' reported by ' + str(self.reported_by)

class Contact_Request(models.Model):
	requested_by = 		models.ForeignKey(User, null = True, on_delete = models.CASCADE, related_name = 'contact_requested_by')
	requested_user = 	models.ForeignKey(User, null = True, on_delete = models.CASCADE, related_name = 'contact_requested_user')

	def __str__(self):
		return str(self.requested_user) + ' requested by ' + str(self.requested_by)

class Complaint_Request(models.Model):
	requested_complaint = 		models.ForeignKey(Complaint, null = True, on_delete = models.CASCADE, related_name = 'complaint_request')
	requested_by = 				models.ForeignKey(User, null = True, on_delete = models.CASCADE, related_name = 'complaint_requested_by')
	requested_user = 			models.ForeignKey(User, null = True, on_delete = models.CASCADE, related_name = 'complaint_requested_user')
	
	def __str__(self):
		return str(self.requested_user) + ' requested by ' + str(self.requested_by)

class Contact_Permission(models.Model):
	permitted_user = 	models.ForeignKey(User, null = True, on_delete = models.CASCADE, related_name = 'permitted_user_permissions')
	permitted_by = 		models.ForeignKey(User, null = True, on_delete = models.CASCADE, related_name = 'permitted_by_permissions')

	def __str__(self):
		return str(self.permitted_user) + ' permitted by ' + str(self.permitted_by)

DV_prevention/user_requests/views.py
from .models import *
from accounts.models import User
from complaints.models import Complaint
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, reverse, redirect
from user_auth.decorators import auth_or_not
# Create your views here.

@login_required(login_url='user_auth:login')
@auth_or_not(1)
def verifyUser(request, profile_id):
	"""
	Verify the identity of a User
	"""
	verified_user = User.objects.get(id = profile_id)
	if(verified_user == request.user):
		return JsonResponse({'verification_post':False})
	if(Verification.objects.filter(verified_user = verified_user, verified_by = request.user).exists()):
		return JsonResponse({'verification_post':False})
	else:
		Verification.objects.create(verified_user = verified_user, verified_by = request.user)
		return JsonResponse({'verification_post':True})

@login_required(login_url='user_auth:login')
@auth_or_not(1)
def reportUser(request, profile_id):
	"""
	Report the identity of a User
	"""
	reported_user = User.objects.get(id = profile_id)
	if(reported_user == request.user):
		return JsonResponse({'verification_post':False})
	if(Report.objects.filter(reported_user = reported_user, reported_by = request.user).exists()):
		return JsonResponse({'report_post':False})
	else:
		Report.objects.create(reported_user = reported_user, reported_by = request.user)
		return JsonResponse({'report_post':True})

from django.contrib.sessions.models import Session
from channels.layers import get_channel_layer
import json
from asgiref.sync import async_to_sync

@login_required(login_url='user_auth:login')
@auth_or_not(1)
def requestContactInfo(request, profile_id):
	"""
	Request a User to view their contact info
	"""
	requested_user = User.objects.get(id = profile_id)
	if(Contact_Request.objects.filter(requested_user = requested_user, requested_by = request.user).exists()):
		return JsonResponse({'request_post':False})
	
	requested_user.user_notifications += 1
	requested_user.save()
	print("Requested to : ", requested_user.user_notifications)

	channel_layer = get_channel_layer()
	# room_name_for_notification = "requests_for_"+str(request.user)

	try:
		async_to_sync(channel_layer.group_send)(
			"notification_requests_for_"+str(requested_user),
			{
				'type': 'send_request_notification',
				'message': json.dumps("Notification")
			}
		)
	except:
		pass
	
	Contact_Request.objects.create(requested_user = requested_user, requested_by = request.user)
	return JsonResponse({'request_post':True})

@login_required(login_url='user_auth:login')
@auth_or_not(1)
def requestComplaintAction(request, profile_id):
	"""
	Request an activist to look into current user's complaint
	"""
	requested_user = User.objects.get(id = profile_id)
	complaint = Complaint.objects.filter(complaint_filer = request.user)[0]
	if(Complaint_Request.objects.filter(requested_by = request.user, requested_user = requested_user, requested_complaint = complaint).exists()):
		return JsonResponse({'request_post':False})
	
	requested_user.user_notifications += 1
	requested_user.save()

	channel_layer = get_channel_layer()
	# room_name_for_notification = "requests_for_"+str(request.user)

	try:
		async_to_sync(channel_layer.group_send)(
			"notification_requests_for_"+str(requested_user),
			{
				'type': 'send_request_notification',
				'message': json.dumps("Notification")
			}
		)
	except:
		pass
	
	Complaint_Request.objects.create(requested_by = request.user, requested_user = requested_user, requested_complaint = complaint)
	return JsonResponse({'request_post':True})

@login_required(login_url='user_auth:login')
@auth_or_not(1)
def showContactRequests(request):
	"""
	See Contact Requests availible for user's profile
	"""
	contact_requests = Contact_Request.objects.filter(requested_user = request.user)
	request.user.user_notifications = 0
	request.user.save()
	context = {'contact_requests':contact_requests, 'True':1, 'False':0}
	return render(request, 'user_requests/contact_requests.html', context)

@login_required(login_url='user_auth:login')
@auth_or_not(1)
def showComplaintRequests(request):
	"""
	See Complaint Requests availible for user's profile
	"""
	complaint_requests_all = Complaint_Request.objects.filter(requested_user = request.user)
	complaints = []
	for i in complaint_requests_all:
		if i.requested_complaint.complaint_status == 'active':
			complaints.append(i.requested_complaint)
	request.user.user_notifications = 0
	request.user.save()
	context = {'complaints':complaints, 'complaint_page_title':'Complaint Requests for '+ str(request.user)}
	return render(request, 'complaints/complaints.html', context)

@login_required(login_url='user_auth:login')
@auth_or_not(1)
def requestContactInfoAction(request, request_id, action):
	"""
	Permit a User to see current user's contact request
	"""
	contact_info_request = Contact_Request.objects.get(id = request_id)
	if(action == 1):
		Contact_Permission.objects.create(permitted_user = contact_info_request.requested_by, 
		permitted_by = request.user)
		Contact_Request.objects.get(id = request_id).delete()
	else:
		Contact_Request.objects.get(id = request_id).delete()
	return redirect('user_requests:show-contact-requests')

DV_prevention/user_requests/templates/user_requests/complaint_requests.html
{% load static %}
{% include 'accounts/main.html' %}

{% block content %}

<style>
  * {
	 box-sizing: border-box;
}
 .blog-card {
	 display: flex;
	 flex-direction: column;
	 margin: 1rem auto;
	 box-shadow: 0 3px 7px -1px rgba(0, 0, 0, .1);
	 margin-bottom: 1.6%;
	 background: #fff;
	 line-height: 1.4;
	 font-family: sans-serif;
	 border-radius: 5px;
	 overflow: hidden;
	 z-index: 0;
}
 .blog-card a {
	 color: inherit;
}
 .blog-card a:hover {
	 color: #5ad67d;
}
 .blog-card:hover .photo {
	 transform: scale(1.3) rotate(3deg);
}
 .blog-card .meta {
	 position: relative;
	 z-index: 0;
	 height: 200px;
}
 .blog-card .photo {
	 position: absolute;
	 top: 0;
	 right: 0;
	 bottom: 0;
	 left: 0;
	 background-size: cover;
	 background-position: center;
	 transition: transform 0.2s;
}
 .blog-card .details, .blog-card .details ul {
	 margin: auto;
	 padding: 0;
	 list-style: none;
}
 .blog-card .details {
	 position: absolute;
	 top: 0;
	 bottom: 0;
	 left: -100%;
	 margin: auto;
	 transition: left 0.2s;
	 background: rgba(0, 0, 0, .6);
	 color: #fff;
	 padding: 10px;
	 width: 100%;
	 font-size: 0.9rem;
}
 .blog-card .details a {
	 text-decoration: dotted underline;
}
 .blog-card .details ul li {
	 display: inline-block;
}
 .blog-card .details .author:before {
	 font-family: FontAwesome;
	 margin-right: 10px;
	 content: "\f007";
}
 .blog-card .details .date:before {
	 font-family: FontAwesome;
	 margin-right: 10px;
	 content: "\f133";
}
 .blog-card .details .tags ul:before {
	 font-family: FontAwesome;
	 content: "\f02b";
	 margin-right: 10px;
}
 .blog-card .details .tags li {
	 margin-right: 2px;
}
 .blog-card .details .tags li:first-child {
	 margin-left: -4px;
}
 .blog-card .description {
	 padding: 1rem;
	 background: #fff;
	 position: relative;
	 z-index: 1;
}
 .blog-card .description h1, .blog-card .description h2 {
	 font-family: Poppins, sans-serif;
}
 .blog-card .description h1 {
	 line-height: 1;
	 margin: 0;
	 font-size: 1.7rem;
}
 .blog-card .description h2 {
	 font-size: 1rem;
	 font-weight: 300;
	 text-transform: uppercase;
	 color: #a2a2a2;
	 margin-top: 5px;
}
 .blog-card .description .read-more {
	 text-align: right;
}
 .blog-card .description .read-more a {
	 color: #5ad67d;
	 display: inline-block;
	 position: relative;
}
 .blog-card .description .read-more a:after {
	 content: "\f061";
	 font-family: FontAwesome;
	 margin-left: -10px;
	 opacity: 0;
	 vertical-align: middle;
	 transition: margin 0.3s, opacity 0.3s;
}
 .blog-card .description .read-more a:hover:after {
	 margin-left: 5px;
	 opacity: 1;
}
 .blog-card p {
	 position: relative;
	 margin: 1rem 0 0;
}
 .blog-card p:first-of-type {
	 margin-top: 1.25rem;
}
 .blog-card p:first-of-type:before {
	 content: "";
	 position: absolute;
	 height: 5px;
	 background: #5ad67d;
	 width: 35px;
	 top: -0.75rem;
	 border-radius: 3px;
}
 .blog-card:hover .details {
	 left: 0%;
}
 @media (min-width: 640px) {
	 .blog-card {
		 flex-direction: row;
		 max-width: 700px;
	}
	 .blog-card .meta {
		 flex-basis: 40%;
		 height: auto;
	}
	 .blog-card .description {
		 flex-basis: 60%;
	}
	 .blog-card .description:before {
		 transform: skewX(-3deg);
		 content: "";
		 background: #fff;
		 width: 30px;
		 position: absolute;
		 left: -10px;
		 top: 0;
		 bottom: 0;
		 z-index: -1;
	}
	 .blog-card.alt {
		 flex-direction: row-reverse;
	}
	 .blog-card.alt .description:before {
		 left: inherit;
		 right: -10px;
		 transform: skew(3deg);
	}
	 .blog-card.alt .details {
		 padding-left: 25px;
	}
}
 
</style>

<style>
	@import url('https://fonts.googleapis.com/css?family=Dosis:300,400,500,600,700,800|Quicksand:300,400,500,700');

html, body{ font-family: 'Quicksand', sans-serif;}
a, a:hover,a:active, a:focus{ text-decoration: none !important; outline: none !important; box-shadow: none; }

/*blog-area*/
.blog-area {background: url(../images/bg-building.jpg) repeat-x;padding: 30px 0;background-position: bottom;animation-name: motion2;animation-duration: 100s;animation-iteration-count: infinite;animation-timing-function: linear;background-size: 100%;}
.blogs-item {width: calc(100%/3 - 30px);float: left;margin: 0 15px; transition: all 0.25s}
.blogs:after {content: '';display: block;clear: both;}
.blog-img .blog-time .blog-month {font-size: 12px;line-height: normal;letter-spacing: 0.5px; font-weight: 500;}
.blog-img .blog-time .blog-date {font-size: 22px;line-height: normal;font-weight: 600;}
.blog-img .blog-time {position: absolute;height: 50px;width: 50px;background: #3c377b;top: 10px;left: 10px;text-align: center;color: #fff;text-transform: uppercase;line-height: normal;margin: 0;}
.blog-img {position: relative;}
.blog-detail{padding: 20px 25px;border: 1px solid #eee;position: relative;overflow: hidden;-webkit-transition: border .4s;-moz-transition: border .4s;-ms-transition: border .4s;transition: border .4s; background: #fff; z-index: 0;}
.blogs-item:hover .blog-detail:after {left: 0;bottom: 0;-webkit-transform: scale(15) translateZ(0);-moz-transform: scale(15) translateZ(0);-ms-transform: scale(15) translateZ(0);-o-transform: scale(15) translateZ(0);transform: scale(15) translateZ(0);}
.blog-detail h4 a {color: #202020;}
.blog-detail h4 {font-size: 18px;line-height: 30px;text-transform: capitalize;font-weight: 500; margin: 0;}
.blog-detail ul li a {color: #676767;}
.blog-detail ul li {font-size: 11px;line-height: 12px;text-transform: uppercase;border-right: 1px solid #e0e0e0;padding-right: 10px;display: inline-block;}
.blog-detail ul {list-style: none;padding: 0;}
.blog-detail ul li:last-child {border: 0; padding-right: 0;}
.blog-detail p {line-height: 25px;font-size: 16px;letter-spacing: .5px;color: #878787;margin: 0;}
.blogs-item .blog-img img {filter: grayscale(0);}
.blogs-item:hover .blog-img img {filter: grayscale(1);}
.blogs {padding: 20px 0;}
.blog-area {padding: 30px 0;}
.read-more-btn a {padding: 10px 25px;display: inline-block;color: #666;border: 1px solid #666;letter-spacing: 1px;text-transform: uppercase;font-weight: 500;box-shadow: 0 3px 0 transparent;transition: 0.3s ease;}
.read-more-btn a:hover {background: #5745ae;border-color: #5745ae;color: #fff;box-shadow: 0 3px 0 #3c377b;}
.read-more-btn {text-align: center;padding: 30px 0 10px;}
.blog-img img{ max-width:100%; height:auto;}
/*end*/
.heading h2 {position: relative;font-weight: 600;font-family: 'Dosis', sans-serif;text-transform: uppercase;padding: 0 0 10px;color: #231f20;}
.heading h2:before {position: absolute;content: '';height: 1px;width: 150px;background: #ffbe00;left: 0;right: 0;bottom: 1px;margin: auto;}
.heading h2:after {content: '';height: 3px;width: 50px;background: #3c377b;position: absolute;left: 0;right: 0;margin: auto;bottom: 0;}
.heading p {color: #878787;}
.heading {text-align: center;padding: 20px 0;max-width: 750px;margin: 0 auto;}
/*hover*/
.hvr-float-shadow {
    display: inline-block;
    vertical-align: middle;
    -webkit-transform: perspective(1px) translateZ(0);
    transform: perspective(1px) translateZ(0);
    box-shadow: 0 0 1px transparent;
    position: relative;
    -webkit-transition-duration: .3s;
    transition-duration: .3s;
    -webkit-transition-property: transform;
    transition-property: transform;
}
.hvr-float-shadow:active, .hvr-float-shadow:focus, .hvr-float-shadow:hover {
    -webkit-transform: translateY(-5px);
    transform: translateY(-5px);
}

.hvr-float-shadow:before {
    pointer-events: none;
    position: absolute;
    z-index: -1;
    content: '';
    top: 100%;
    left: 5%;
    height: 10px;
    width: 90%;
    opacity: 0;
    background: -webkit-radial-gradient(center,ellipse,rgba(0,0,0,.35) 0,transparent 80%);
    background: radial-gradient(ellipse at center,rgba(0,0,0,.35) 0,transparent 80%);
    -webkit-transition-duration: .3s;
    transition-duration: .3s;
    -webkit-transition-property: transform,opacity;
    transition-property: transform,opacity;
}

.hvr-float-shadow:active:before, .hvr-float-shadow:focus:before, .hvr-float-shadow:hover:before {
    opacity: 1;
    -webkit-transform: translateY(5px);
    transform: translateY(5px);
}

/*media*/

@media (max-width:991px){
    .blogs-item {width: calc(100%/2 - 30px);margin: 0 15px 30px;}
}


@media (max-width:767px){
    .blogs-item {width: 100%;margin: 0 auto 30px;max-width: 470px;display: block;float: none;}
    .read-more-btn {padding: 0 0 10px;}
}

@media (max-width:400px){
    .blog-detail {padding:20px;}
}

.example::-webkit-scrollbar {
  display: none;
}

/* Hide scrollbar for IE, Edge and Firefox */
.scrolling-wrapper {
  -ms-overflow-style: none;  /* IE and Edge */
  scrollbar-width: none;  /* Firefox */
}

#cropped-description {
  overflow:hidden; height: 200px; text-overflow:ellipsis;
}

#cropped-tags {
  overflow:hidden; 
  white-space:nowrap; 
  text-overflow:ellipsis;
}

</style>

<div class="container mt-5 mb-5">
  <section class="blog-area">
    <div class="container">
      <div class="heading">
      <h2>Complaints</h2>
      </div>
      <div class="blogs">
        <div class="row">
        {% for complaint in complaint_requests %}
          <div class="blogs-item hvr-float-shadow wow fadeInLeft h-100 mb-5" data-wow-delay="0.5s">
            <div class="blog-img photo">
              <a href="{% url 'complaints:show-complaint-detail' complaint.id %}"><img src="{% static 'images/' %}{{complaint.complaint_request_image}}" alt="" class="img-fluid"></a>
              <p class="blog-time">
              <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
              <span class="blog-date"><i class="fa fa-solid fa-chevron-up"></i></span>
              <br>
              <span class="blog-month">{{complaint.complaint_upvotes}}</span>
              </p>
            </div>
            <div class="blog-detail">
              <h4><a href="javascript:;">{{complaint.complaint_title}}</a></h4>
              <ul class="scrolling-wrapper" id="cropped-tags">
                {% for tag in complaint.tags.all %}
                <li><a href="javascript:;">#{{ tag }}</a></li>
                {% endfor %}
              </ul>
              <p class="scrolling-wrapper" id="cropped-description">{{complaint.complaint_description}}</p>...
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </section>
</div>

{% endblock %}

<!--<div class="read-more-btn">
            <a href="javascript:;" class="hvr-float-shadow">Read More</a>
        </div>-->

DV_prevention/user_requests/templates/user_requests/contact_requests.html
{% load static %}
{% include 'accounts/main.html' %}

{% block content %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="container mt-5 mb-5">
    <div class="d-flex justify-content-center row">
        <div class="col-md-10">
            {% for contact_request in contact_requests %}
            <div class="row p-2 bg-white border rounded">
                <div class="col-md-6 mt-1">
                    <h5>By: </h5>
                    <a href="{% url 'accounts:profile-view' contact_request.requested_by.slug %}"><h3>{{contact_request.requested_by}}</h5></a>
                    <div class="d-flex flex-row">
                    </div>
                    <p class="text-justify para mb-0">{{contact_request.request_note}}<br><br></p>
                </div>
                <div class="col-md-3 mt-1">
                </div>
                <div class="col-md-3">
                    <a href="{% url 'user_requests:request-contact-info-action' contact_request.id True %}">
                        <button class="btn btn-success m-1 mt-3" style="width: 100%;">
                            <i class="fa fa-check"></i> Accept
                        </button>
                    </a>
                    <a href="{% url 'user_requests:request-contact-info-action' contact_request.id False %}">
                        <button class="btn btn-danger m-1 mt-3" style="width: 100%;">
                            <strong>X</strong> Deny
                        </button>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}